language: cpp

env:
  global:
    - ARDUINO_VERSION="1.6.8"
  matrix:
    - PLATFORM='arduino:avr'  BOARD='uno'
    - PLATFORM='arduino:avr'  BOARD='mega:cpu=atmega2560'
    - PLATFORM='arduino:avr'  BOARD='leonardo'
    - PLATFORM='arduino:sam'  BOARD='arduino_due_x_dbg'
#   - PLATFORM='arduino:samd' BOARD='arduino_zero_edbg'
    - PLATFORM='Intel:i586'   BOARD='izmir_fd'
    - PLATFORM='Intel:i586'   BOARD='izmir_fg'

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$(eval echo $ARDUINO_VERSION)-linux64.tar.xz
  - tar xf arduino-$(eval echo $ARDUINO_VERSION)-linux64.tar.xz
  - sudo mv arduino-$(eval echo $ARDUINO_VERSION) /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  - mkdir build

install:
  - arduino --install-boards $PLATFORM > /dev/null
  - ln -s $PWD /usr/local/share/arduino/libraries/OneSheeld

before_script:
  - arduino --pref build.path=$PWD/build --board $PLATFORM:$BOARD --save-prefs

script:
  - arduino --verify $PWD/examples/Advanced/Accelerometer/Accelerometer.ino
  - arduino --verify $PWD/examples/Advanced/Buzzer/Buzzer.ino
  - arduino --verify $PWD/examples/Advanced/Camera/Camera.ino
  - arduino --verify $PWD/examples/Advanced/Clock/Clock.ino
  - arduino --verify $PWD/examples/Advanced/Color/Color.ino
  - arduino --verify $PWD/examples/Advanced/Email/Email.ino
  - arduino --verify $PWD/examples/Advanced/Facebook/Facebook.ino
  - arduino --verify $PWD/examples/Advanced/Foursquare/Foursquare.ino
  - arduino --verify $PWD/examples/Advanced/GamePad/GamePad.ino
  - arduino --verify $PWD/examples/Advanced/GLCD/GLCD.ino
  - arduino --verify $PWD/examples/Advanced/GPS/GPS.ino
  - arduino --verify $PWD/examples/Advanced/Gravity/Gravity.ino
  - arduino --verify $PWD/examples/Advanced/Internet/Internet.ino
  - arduino --verify $PWD/examples/Advanced/Keypad/Keypad.ino
  - arduino --verify $PWD/examples/Advanced/LCD/LCD.ino
  - arduino --verify $PWD/examples/Advanced/Light/Light.ino
  - arduino --verify $PWD/examples/Advanced/Magnetometer/Magnetometer.ino
  - arduino --verify $PWD/examples/Advanced/Mic/Mic.ino
  - arduino --verify $PWD/examples/Advanced/MusicPlayer/MusicPlayer.ino
  - arduino --verify $PWD/examples/Advanced/NFC/NFC.ino
  - arduino --verify $PWD/examples/Advanced/Notification/Notification.ino
  - arduino --verify $PWD/examples/Advanced/Orientation/Orientation.ino
  - arduino --verify $PWD/examples/Advanced/Phone/Phone.ino
  - arduino --verify $PWD/examples/Advanced/Pressure/Pressure.ino
  - arduino --verify $PWD/examples/Advanced/Proximity/Proximity.ino
  - arduino --verify $PWD/examples/Advanced/SevenSegment/SevenSegment.ino
  - arduino --verify $PWD/examples/Advanced/Skype/Skype.ino
  - arduino --verify $PWD/examples/Advanced/SMS/SMS.ino
  - arduino --verify $PWD/examples/Advanced/TextToSpeech/TextToSpeech.ino
  - arduino --verify $PWD/examples/Advanced/ToggleButton/ToggleButton.ino
  - arduino --verify $PWD/examples/Advanced/Twitter/Twitter.ino
  - arduino --verify $PWD/examples/Advanced/Vibration/Vibration.ino
  - arduino --verify $PWD/examples/Advanced/VoiceRecognition/VoiceRecognition.ino
  - arduino --verify $PWD/examples/Simple/Accelerometer/Accelerometer.ino
  - arduino --verify $PWD/examples/Simple/Buzzer/Buzzer.ino
  - arduino --verify $PWD/examples/Simple/Camera/Camera.ino
  - arduino --verify $PWD/examples/Simple/Color/Color.ino
  - arduino --verify $PWD/examples/Simple/DataLogger/DataLogger.ino
  - arduino --verify $PWD/examples/Simple/Facebook/Facebook.ino
  - arduino --verify $PWD/examples/Simple/Foursquare/Foursquare.ino
  - arduino --verify $PWD/examples/Simple/GamePad/GamePad.ino
  - arduino --verify $PWD/examples/Simple/GLCD/GLCD.ino
  - arduino --verify $PWD/examples/Simple/Gravity/Gravity.ino
  - arduino --verify $PWD/examples/Simple/Gyroscope/Gyroscope.ino
  - arduino --verify $PWD/examples/Simple/Internet/Internet.ino
  - arduino --verify $PWD/examples/Simple/Keyboard/Keyboard.ino
  - arduino --verify $PWD/examples/Simple/Keypad/Keypad.ino
  - arduino --verify $PWD/examples/Simple/Led/Led.ino
  - arduino --verify $PWD/examples/Simple/Light/Light.ino
  - arduino --verify $PWD/examples/Simple/Magnetometer/Magnetometer.ino
  - arduino --verify $PWD/examples/Simple/Mic/Mic.ino
  - arduino --verify $PWD/examples/Simple/MusicPlayer/MusicPlayer.ino
  - arduino --verify $PWD/examples/Simple/NFC/NFC.ino
  - arduino --verify $PWD/examples/Simple/Notification/Notification.ino
  - arduino --verify $PWD/examples/Simple/Orientation/Orientation.ino
  - arduino --verify $PWD/examples/Simple/Pattern/Pattern.ino
  - arduino --verify $PWD/examples/Simple/Phone/Phone.ino
  - arduino --verify $PWD/examples/Simple/Proximity/Proximity.ino
  - arduino --verify $PWD/examples/Simple/PushButton/PushButton.ino
  - arduino --verify $PWD/examples/Simple/Slider/Slider.ino
  - arduino --verify $PWD/examples/Simple/Temperature/Temperature.ino
  - arduino --verify $PWD/examples/Simple/Terminal/Terminal.ino
  - arduino --verify $PWD/examples/Simple/Twitter/Twitter.ino
  - arduino --verify $PWD/examples/Simple/Vibration/Vibration.ino
  - arduino --verify $PWD/examples/Simple/VoiceRecognition/VoiceRecognition.ino
#  - for example in $PWD/examples/*/*/*.ino; do arduino --verify $example; done;
#  - find $PWD/examples -type f -name "*.ino" -exec arduino --verify {} \; 

notifications:
  email:
    on_success: change
    on_failure: change